apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coworking
  region: us-east-1

managedNodeGroups:
  - name: cw-spot-nodes
    instanceTypes:
      - t3.small
      - t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    spot: true
    volumeSize: 20
    labels:
      instance-type: spot
    tags:
      nodegroup-type: spot
    iam:
      withAddonPolicies:
        autoScaler: true
